### ISSUE TITLE
Broken animations when collapsible element is styled by parent-scoped selectors

### ISSUE THREAD

**Issue by Wsiegenthaler** [plong0/angular-collapse#1]
When collapsing or expanding an element it's natural size must be determined in order to properly set the start/end keyframes. To do this, getRenderSize() temporarily adds a clone of the element to the document body in order to resolve the width and height.

But if the size of the element is determined by styles whose selectors expect certain parents then those styles will not be applied to the cloned element used to determine render size. This leads to bad values for the elements true size and broken animation.

**Comment by plong0** [comment]
Merged.  Thank you for the fix.
